### Create todo
POST http://localhost:5000/api/todos
Content-Type: application/json

{
  "body": "Learn Go"
}

### Get all todos
GET http://localhost:5000/api/todos

### Patch todo by id
PATCH  http://localhost:5000/api/todos/68a44b54033f8714aa0d0cdc

### Delete todo by id
DELETE http://localhost:5000/api/todos/68a55793a9fd95d1b3e705ab



