### Create todo
POST http://localhost:5000/api/todos
Content-Type: application/json

{
  "body": "Learn React"
}

### Get all todos
GET http://localhost:5000/api/todos

### Patch todo by id
PATCH  http://localhost:5000/api/todos/1

### Delete todo by id
DELETE http://localhost:5000/api/todos/4


